site_name: OpenEMP
theme:
  name: material
  language: en
  logo: images/openemp.svg
  palette:
    primary: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
markdown_extensions:
  - pymdownx.emoji
  - admonition
  - codehilite
  - toc:
      toc_depth: 3
nav:
  - Introduction: 'index.md'
  - Getting Started:
      - Run OpenEMP: 'getting-started/start.md'
  - User Guide: 'user/index.md'
  - Implementer Guide: 'implementer/index.md'
  - Developer Guide: 'dev/index.md'
    - API documentation :
      - USER API: 'services/users.md' 
  - Contribution:
    - Code of Conduct: 'contribution/code-of-conduct.md'
    - How To Contribute: 'contribution/how-to-contribute.md'
  - About:
    - Get in touch: 'about/contact.md'
    - License: 'about/license.md'
