site_name: OpenEMP
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
markdown_extensions:
  - codehilite
  - toc:
      toc_depth: 3
nav:
  - Introduction: 'index.md'
  - Getting Started:
      - Run OpenEMP: 'getting-started/start.md'
  - User Guide: ''
  - Implementer Guide: ''
  - Developer Guide: ''
  - Contribution:
    - Code of Conduct: 'contribution/code-of-conduct.md'
    - How To Contribute: 'contribution/how-to-contribute.md'
  - OpenEMP Services:
    - User Service: 'services/users.md'
  - About:
    - Get in touch: 'about/contact.md'
    - License: 'about/license.md'
